
import json
from pathlib import Path
from super.apps.generate_powers.models import MutatedGene
from super.apps.generate_powers.models_hero import HeroProfile

def export_schema(output_path: Path):
    # 1. Generate JSON Schemas from Pydantic
    profile_schema = HeroProfile.model_json_schema()
    genome_schema = MutatedGene.model_json_schema()
    
    # 2. Structure the output
    # We want to document what files look like.
    # Profile file = single HeroProfile object
    # Genome file = list of MutatedGene objects, or single? 
    # generate_genome.py writes LIST of MutatedGene to single JSON usually, 
    # but ad_hoc.py iterates "genes_data" from file json.load(fh).
    # If json.load returns a list, then it's a list.
    # We will document the Item schema and note it is a list.
    
    full_schema = {
        "title": "Super Powers Ingestion Schema",
        "description": "Schema for raw JSON artifacts generated by the Agent/LLM and ingested by ETL.",
        "artifacts": {
            "hero_profile": {
                "file_pattern": "data/generated_genome/hero_profiles/{ontology}/{hero_name}.json",
                "description": "High-level hero metadata and seed selection.",
                "schema": profile_schema
            },
            "hero_genome": {
                "file_pattern": "data/generated_genome/hero_genomes/{ontology}/{hero_name}.json",
                "description": "Detailed gene regulatory network (List of Genes).",
                "schema": {
                    "type": "array",
                    "items": genome_schema
                }
            }
        }
    }
    
    # 3. Write to file
    with open(output_path, "w") as f:
        json.dump(full_schema, f, indent=2)
        
    print(f"Ingestion schema exported to: {output_path}")

if __name__ == "__main__":
    import sys
    # Default location
    default_out = Path(__file__).parents[5] / "data" / "ingestion_schema.json"
    
    if len(sys.argv) > 1:
        out = Path(sys.argv[1])
    else:
        out = default_out
        
    export_schema(out)
